server:
  port: 2008
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root1
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin


  mail:
    host: smtp.gmail.com
    port: 587
    username: pro.vd14@gmail.com
    password: tfvs mkic blur bpuy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true